// Package agenttoken maintains the persistent agent directory and per-agent access
// credentials that can be rotated and deleted independently.
// The credential plaintext appears only once in the issuance response; only its SHA-256 is stored.
package agenttoken

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	"github.com/google/uuid"
	"github.com/liveagent/agent-gateway/internal/db"
)

// tokenPrefix makes the credential type easy to recognize at a glance in logs/config (not used in validation).
const tokenPrefix = "agt_"

// tokenEntropyBytes is the number of bytes in the credential's random part (32 bytes ≈ 43 base64url characters).
const tokenEntropyBytes = 32

const maxAgentNameLength = 64

var ErrAgentIDRequired = errors.New("agent id is required")

var ErrInvalidAgentID = errors.New("agent id must be a canonical agent UUID v4")

var ErrAgentNameTooLong = errors.New("agent name must not exceed 64 characters")

var ErrAgentNotFound = errors.New("agent not found")

var ErrInvalidStatusFilter = errors.New("invalid agent status filter")

var ErrUnauthorized = errors.New("unauthorized agent credential")

// dummyHashHex is the placeholder hash compared against when the agent_id is unknown (same
// length as real hashes and never matching), so validation takes the same time for an unknown id
// as for a bad credential and does not reveal whether an id exists.
var dummyHashHex = strings.Repeat("0", sha256.Size*2)

// DirectoryEntry is a persisted agent directory entry.
type DirectoryEntry struct {
	AgentID        string
	Name           string
	RegisteredAt   time.Time
	HasToken       bool
	TokenCreatedAt time.Time
}

// Store is the handle to the agent directory and credential subsystem; it is created at Gateway startup and is always available.
type Store struct {
	pool             *sql.DB
	knownAgents      sync.Map
	credentialMu     sync.RWMutex
	credentialEpochs map[string]uint64
}

// NewStore initializes the initial agents table schema on the Gateway's shared database.
func NewStore(database *db.DB) (*Store, error) {
	if database == nil || !database.Enabled() {
		return nil, errors.New("gateway database is required")
	}
	pool := database.Pool()
	if _, err := pool.Exec(`
		CREATE TABLE IF NOT EXISTS agents (
			agent_id        TEXT PRIMARY KEY,
			name            TEXT NOT NULL DEFAULT '' CHECK (length(name) <= 64),
			token_sha256    TEXT,
			created_at      INTEGER NOT NULL,
			token_issued_at INTEGER,
			CHECK ((token_sha256 IS NULL) = (token_issued_at IS NULL))
		);
		CREATE INDEX IF NOT EXISTS idx_agents_created_at_agent_id
			ON agents(created_at, agent_id);
	`); err != nil {
		return nil, fmt.Errorf("init agent schema: %w", err)
	}
	store := &Store{pool: pool, credentialEpochs: make(map[string]uint64)}
	if err := store.loadKnownAgents(); err != nil {
		return nil, err
	}
	return store, nil
}

// loadKnownAgents restores the registered-ID cache once before the Gateway starts listening. It
// reads only primary keys and does not cache credentials; rotation and revocation of individual
// tokens are still enforced by the database check on every connection.
func (s *Store) loadKnownAgents() error {
	rows, err := s.pool.Query(`SELECT agent_id FROM agents`)
	if err != nil {
		return fmt.Errorf("load known agents: %w", err)
	}
	for rows.Next() {
		var agentID string
		if err := rows.Scan(&agentID); err != nil {
			_ = rows.Close()
			return fmt.Errorf("load known agents: %w", err)
		}
		s.knownAgents.Store(agentID, struct{}{})
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return fmt.Errorf("load known agents: %w", err)
	}
	if err := rows.Close(); err != nil {
		return fmt.Errorf("load known agents: %w", err)
	}
	return nil
}

// NormalizeAgentID accepts the canonical agent-UUIDv4 identifier auto-generated by the desktop client.
func NormalizeAgentID(raw string) (string, error) {
	agentID := strings.TrimSpace(raw)
	if agentID == "" {
		return "", ErrAgentIDRequired
	}
	const prefix = "agent-"
	if !strings.HasPrefix(agentID, prefix) {
		return "", ErrInvalidAgentID
	}
	parsed, err := uuid.Parse(strings.TrimPrefix(agentID, prefix))
	if err != nil || parsed.Version() != 4 || prefix+parsed.String() != agentID {
		return "", ErrInvalidAgentID
	}
	return agentID, nil
}

func normalizeName(raw string) (string, error) {
	name := strings.TrimSpace(raw)
	if utf8.RuneCountInString(name) > maxAgentNameLength {
		return "", ErrAgentNameTooLong
	}
	return name, nil
}

// Pagination defaults and limits (following the clamping style of the project's history list).
const (
	defaultPageSize = 50
	maxPageSize     = 200
)

// StatusFilter is the live online-status filter for the agent directory.
type StatusFilter string

const (
	StatusAll     StatusFilter = "all"
	StatusOnline  StatusFilter = "online"
	StatusOffline StatusFilter = "offline"
)

// ParseStatusFilter parses the admin API status filter; an empty value is equivalent to all.
func ParseStatusFilter(raw string) (StatusFilter, error) {
	filter := StatusFilter(strings.ToLower(strings.TrimSpace(raw)))
	if filter == "" {
		return StatusAll, nil
	}
	switch filter {
	case StatusAll, StatusOnline, StatusOffline:
		return filter, nil
	default:
		return "", ErrInvalidStatusFilter
	}
}

// PageParams holds pagination inputs; both status filtering and pagination are performed by SQLite.
type PageParams struct {
	Page           int
	PageSize       int
	Status         StatusFilter
	OnlineAgentIDs []string
}

func (p PageParams) normalized() (page, pageSize, offset int) {
	page = p.Page
	if page < 1 {
		page = 1
	}
	pageSize = p.PageSize
	switch {
	case pageSize <= 0:
		pageSize = defaultPageSize
	case pageSize > maxPageSize:
		pageSize = maxPageSize
	}
	return page, pageSize, (page - 1) * pageSize
}

// Page is one page of the agent directory plus pagination metadata.
type Page struct {
	Entries  []DirectoryEntry
	Total    int
	Page     int
	PageSize int
	HasMore  bool
}

func (s *Store) validateLocked(agentID, token string) (bool, error) {
	agentID = strings.TrimSpace(agentID)
	token = strings.TrimSpace(token)
	if agentID == "" || token == "" {
		return false, nil
	}

	stored := dummyHashHex
	known := false
	var fetched sql.NullString
	err := s.pool.QueryRow(`SELECT token_sha256 FROM agents WHERE agent_id = ?`, agentID).Scan(&fetched)
	if err == nil && fetched.Valid && fetched.String != "" {
		stored = fetched.String
		known = true
	}

	presented := sha256.Sum256([]byte(token))
	presentedHex := hex.EncodeToString(presented[:])
	valid := subtle.ConstantTimeCompare([]byte(presentedHex), []byte(stored)) == 1 && known
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return false, fmt.Errorf("query agent credential: %w", err)
	}
	return valid, nil
}

// Register persists an agent on its first successful connection. IDs already known in-process do
// not touch the database; on a cache miss, INSERT OR IGNORE atomically records the agent, avoiding
// WAL updates from repeated connections.
func (s *Store) Register(agentID string) error {
	if s == nil {
		return errors.New("agent registry is not enabled")
	}
	s.credentialMu.RLock()
	defer s.credentialMu.RUnlock()
	return s.registerLocked(agentID)
}

func (s *Store) registerLocked(agentID string) error {
	agentID = strings.TrimSpace(agentID)
	if agentID == "" {
		return ErrAgentIDRequired
	}
	if _, known := s.knownAgents.Load(agentID); known {
		return nil
	}
	if _, err := s.pool.Exec(
		`INSERT OR IGNORE INTO agents (agent_id, name, created_at) VALUES (?, '', ?)`,
		agentID, time.Now().Unix(),
	); err != nil {
		return fmt.Errorf("register agent: %w", err)
	}
	s.knownAgents.Store(agentID, struct{}{})
	return nil
}

// AuthenticateAndRegister performs individual credential validation and directory registration
// under the credential-change read lock, and returns the current credential epoch. sharedAuthenticated
// may only come from the constant-time validation result of the gateway's shared token.
// Issue/Delete must wait for this method to exit, avoiding the window where "the old credential was
// validated but registration happens after rotation".
func (s *Store) AuthenticateAndRegister(
	agentID, token string,
	sharedAuthenticated bool,
) (uint64, error) {
	if s == nil {
		return 0, errors.New("agent token store is not enabled")
	}
	s.credentialMu.RLock()
	defer s.credentialMu.RUnlock()
	if !sharedAuthenticated {
		valid, err := s.validateLocked(agentID, token)
		if err != nil {
			return 0, err
		}
		if !valid {
			return 0, ErrUnauthorized
		}
	}
	if err := s.registerLocked(agentID); err != nil {
		return 0, err
	}
	return s.credentialEpochs[strings.TrimSpace(agentID)], nil
}

// AuthenticationCurrent lets a session confirm under the registration lock that no credential
// rotation or deletion for the same agent occurred between authentication and registration;
// concurrent management operations on different agents do not interfere with each other.
func (s *Store) AuthenticationCurrent(agentID string, epoch uint64) bool {
	if s == nil {
		return false
	}
	s.credentialMu.RLock()
	defer s.credentialMu.RUnlock()
	return s.credentialEpochs[strings.TrimSpace(agentID)] == epoch
}

// Issue generates a new credential for agent_id and persists it, returning the plaintext (this once only); any existing credential is rotated out.
func (s *Store) Issue(agentID, name string) (string, error) {
	if s == nil {
		return "", errors.New("agent token store is not enabled")
	}
	agentID = strings.TrimSpace(agentID)
	if agentID == "" {
		return "", ErrAgentIDRequired
	}
	var err error
	name, err = normalizeName(name)
	if err != nil {
		return "", err
	}

	buf := make([]byte, tokenEntropyBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate agent token: %w", err)
	}
	token := tokenPrefix + base64.RawURLEncoding.EncodeToString(buf)
	digest := sha256.Sum256([]byte(token))
	now := time.Now().Unix()

	s.credentialMu.Lock()
	defer s.credentialMu.Unlock()
	if _, err := s.pool.Exec(
		`INSERT INTO agents (agent_id, name, token_sha256, created_at, token_issued_at)
		 VALUES (?, ?, ?, ?, ?)
		 ON CONFLICT(agent_id) DO UPDATE SET
		   name = excluded.name,
		   token_sha256 = excluded.token_sha256,
		   token_issued_at = excluded.token_issued_at`,
		agentID, name, hex.EncodeToString(digest[:]), now, now,
	); err != nil {
		return "", fmt.Errorf("persist agent credential: %w", err)
	}
	s.knownAgents.Store(agentID, struct{}{})
	s.credentialEpochs[agentID] += 1
	return token, nil
}

// UpdateName changes the optional name of a registered agent.
func (s *Store) UpdateName(agentID, name string) error {
	if s == nil {
		return ErrAgentNotFound
	}
	agentID = strings.TrimSpace(agentID)
	if agentID == "" {
		return ErrAgentIDRequired
	}
	name, err := normalizeName(name)
	if err != nil {
		return err
	}
	s.credentialMu.RLock()
	defer s.credentialMu.RUnlock()
	result, err := s.pool.Exec(`UPDATE agents SET name = ? WHERE agent_id = ?`, name, agentID)
	if err != nil {
		return fmt.Errorf("update agent name: %w", err)
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("update agent name: %w", err)
	}
	if affected == 0 {
		return ErrAgentNotFound
	}
	return nil
}

// Delete removes the agent directory row and its individual credential.
func (s *Store) Delete(agentID string) (bool, error) {
	if s == nil {
		return false, nil
	}
	agentID = strings.TrimSpace(agentID)
	if agentID == "" {
		return false, ErrAgentIDRequired
	}
	s.credentialMu.Lock()
	defer s.credentialMu.Unlock()
	result, err := s.pool.Exec(`DELETE FROM agents WHERE agent_id = ?`, agentID)
	if err != nil {
		return false, fmt.Errorf("delete agent: %w", err)
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return false, fmt.Errorf("delete agent: %w", err)
	}
	if affected > 0 {
		s.knownAgents.Delete(agentID)
		s.credentialEpochs[agentID] += 1
	}
	return affected > 0, nil
}

// Count returns the total number of persisted agents in the directory.
func (s *Store) Count() (int, error) {
	if s == nil {
		return 0, nil
	}
	var total int
	if err := s.pool.QueryRow(`SELECT COUNT(*) FROM agents`).Scan(&total); err != nil {
		return 0, fmt.Errorf("count agents: %w", err)
	}
	return total, nil
}

// List returns the agent directory filtered by status and paginated. Online IDs are passed to
// SQLite as a single JSON argument expanded by json_each, avoiding the dynamic IN-parameter
// limit; the Go layer never reads all credentials before paginating.
func (s *Store) List(params PageParams) (Page, error) {
	page, pageSize, offset := params.normalized()
	if s == nil {
		return Page{Page: page, PageSize: pageSize}, nil
	}

	filter, err := ParseStatusFilter(string(params.Status))
	if err != nil {
		return Page{}, err
	}
	whereClause := ""
	var filterArg any
	switch filter {
	case StatusOnline, StatusOffline:
		onlineIDs := params.OnlineAgentIDs
		if onlineIDs == nil {
			onlineIDs = []string{}
		}
		encoded, marshalErr := json.Marshal(onlineIDs)
		if marshalErr != nil {
			return Page{}, fmt.Errorf("encode online agent ids: %w", marshalErr)
		}
		filterArg = string(encoded)
		if filter == StatusOnline {
			whereClause = ` WHERE a.agent_id IN (
				SELECT CAST(value AS TEXT) FROM json_each(?)
			)`
		} else {
			whereClause = ` WHERE a.agent_id NOT IN (
				SELECT CAST(value AS TEXT) FROM json_each(?)
			)`
		}
	}

	countQuery := `SELECT COUNT(*) FROM agents AS a` + whereClause
	var total int
	if filter == StatusAll {
		err = s.pool.QueryRow(countQuery).Scan(&total)
	} else {
		err = s.pool.QueryRow(countQuery, filterArg).Scan(&total)
	}
	if err != nil {
		return Page{}, fmt.Errorf("count filtered agents: %w", err)
	}

	listQuery := `SELECT a.agent_id, a.name, a.created_at, a.token_issued_at
		FROM agents AS a` + whereClause +
		` ORDER BY a.created_at, a.agent_id LIMIT ? OFFSET ?`

	var rows *sql.Rows
	if filter == StatusAll {
		rows, err = s.pool.Query(listQuery, pageSize, offset)
	} else {
		rows, err = s.pool.Query(listQuery, filterArg, pageSize, offset)
	}
	if err != nil {
		return Page{}, fmt.Errorf("list filtered agent registry: %w", err)
	}
	defer func() { _ = rows.Close() }()

	entries := make([]DirectoryEntry, 0, pageSize)
	for rows.Next() {
		var entry DirectoryEntry
		var registeredAt int64
		var tokenCreatedAt sql.NullInt64
		if err := rows.Scan(&entry.AgentID, &entry.Name, &registeredAt, &tokenCreatedAt); err != nil {
			return Page{}, fmt.Errorf("scan agent directory: %w", err)
		}
		entry.RegisteredAt = time.Unix(registeredAt, 0).UTC()
		entry.HasToken = tokenCreatedAt.Valid
		if tokenCreatedAt.Valid {
			entry.TokenCreatedAt = time.Unix(tokenCreatedAt.Int64, 0).UTC()
		}
		entries = append(entries, entry)
	}
	if err := rows.Err(); err != nil {
		return Page{}, fmt.Errorf("iterate agent directory: %w", err)
	}

	return Page{
		Entries:  entries,
		Total:    total,
		Page:     page,
		PageSize: pageSize,
		HasMore:  offset+len(entries) < total,
	}, nil
}

// Registered returns all persisted agents (ordered by agent_id), used by the WS agent selector to
// fill in offline entries; the admin page's large directory view must use the database-paginated List.
func (s *Store) Registered() ([]DirectoryEntry, error) {
	if s == nil {
		return nil, errors.New("agent registry is not enabled")
	}
	rows, err := s.pool.Query(`SELECT agent_id, name, created_at FROM agents ORDER BY agent_id`)
	if err != nil {
		return nil, fmt.Errorf("query agent directory: %w", err)
	}
	defer func() { _ = rows.Close() }()

	var out []DirectoryEntry
	for rows.Next() {
		var entry DirectoryEntry
		var createdAt int64
		if err := rows.Scan(&entry.AgentID, &entry.Name, &createdAt); err != nil {
			return nil, fmt.Errorf("scan agent directory: %w", err)
		}
		entry.RegisteredAt = time.Unix(createdAt, 0).UTC()
		out = append(out, entry)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate agent directory: %w", err)
	}
	return out, nil
}
