import { createHostTranslations, type Locale } from "@liveagent/ui/i18n/hostTranslations";

export type { Locale } from "@liveagent/ui/i18n/hostTranslations";
export {
  DEFAULT_LOCALE,
  detectSystemLocale,
  normalizeLocale,
  SUPPORTED_LOCALES,
} from "@liveagent/ui/i18n/hostTranslations";

/**
 * Host translation overrides. Shared, host-neutral messages live in agent-ui.
 */
export const WEBUI_TRANSLATION_OVERRIDES: Record<Locale, Record<string, string>> = {
  "zh-CN": {
    "app.desktopSettingsSyncFailed": "Failed to sync desktop settings.",
    "app.webSettingsSaveFailed": "Failed to save WebUI settings.",
    "chat.runtime.settingsSyncTitle": "Syncing desktop settings",
    "chat.runtime.protocolIncompatible":
      "This desktop version does not support reliable chat sync. Update ReactorPro desktop before using WebUI chat.",
    "chat.runtime.protocolIncompatiblePlaceholder": "Update ReactorPro desktop to continue",
    "chat.queue.moveDown": "Move down",
    "chat.upload.maxFilesIgnored": "Upload up to {max} files; {count} extra files were ignored",
    "chat.upload.duplicatesMerged": "Merged {count} duplicate files",
    "projectTools.sshLocalForwardHelp":
      "Listens on the desktop machine's 127.0.0.1 only. Leave the local port empty or 0 for auto-assign; leave the remote host empty for 127.0.0.1 on the SSH server.",
    "projectTools.sshLocalForwardListening": "Listening on the desktop machine only",
    "settings.navAgentManagement": "Multi-client Management",
    "settings.devicesTitle": "Multi-client Management",
    "settings.devicesDesc": "Manage Agents connected to this Gateway and their credentials",
    "settings.devicesRefresh": "Refresh",
    "settings.devicesFilterAll": "All",
    "settings.devicesFilterOnline": "Online",
    "settings.devicesFilterOffline": "Offline",
    "settings.devicesFilterEmpty": "No matching clients",
    "settings.devicesFilterEmptyDesc": "Choose another status or refresh and try again.",
    "settings.devicesLoginTitle": "Verify Gateway Token",
    "settings.devicesLoginDesc":
      "The current login is unavailable. Enter the Gateway Token again to continue.",
    "settings.devicesGatewayToken": "Gateway Token",
    "settings.devicesLogin": "Verify",
    "settings.devicesAdd": "Add client",
    "settings.devicesAddTitle": "Add client",
    "settings.devicesAddDesc":
      "Enter the Agent ID generated by the client and issue an independent credential.",
    "settings.devicesName": "Client name",
    "settings.devicesNamePlaceholder": "Optional, for example Office desktop",
    "settings.devicesAgentId": "Agent ID",
    "settings.devicesAgentIdPlaceholder": "Paste the agent-UUID generated by the client",
    "settings.devicesIssueShort": "Issue",
    "settings.devicesRotate": "Rotate",
    "settings.devicesRotateTitle": "Rotate client credential?",
    "settings.devicesRotateDesc":
      "Rotation immediately disconnects the client. The old credential cannot reconnect, and the new plaintext is shown once.",
    "settings.devicesEditName": "Edit",
    "settings.devicesIssuedTitle": "Client credential issued",
    "settings.devicesTokenOnce":
      "This token can be reused for client connections, but its plaintext is shown only once. Copy and store it now.",
    "settings.devicesEmpty": "No registered clients",
    "settings.devicesEmptyDesc":
      "Connect a client or select Add client to issue an independent credential.",
    "settings.devicesLoading": "Loading clients…",
    "settings.devicesOnlineStatus": "Online",
    "settings.devicesOfflineStatus": "Offline",
    "settings.devicesUnknownStatus": "Checking status",
    "settings.devicesIndependentTokenIssued": "Independent credential issued",
    "settings.devicesIndependentTokenMissing": "No independent credential",
    "settings.devicesDelete": "Delete",
    "settings.devicesDeleteTitle": "Delete client?",
    "settings.devicesDeleteDesc":
      "This deletes the record, invalidates its credential, and closes its connection. A client using the shared Gateway Token may register again automatically:",
    "settings.devicesPage": "Page",
    "settings.devicesPrevious": "Previous",
    "settings.devicesNext": "Next",
    "settings.devicesLoadFailed": "Failed to load clients.",
    "settings.devicesIssueFailed": "Failed to issue client credential.",
    "settings.devicesNameUpdateFailed": "Failed to update the client name.",
    "settings.devicesDeleteFailed": "Failed to delete the client.",
    "settings.devicesTokenRequired": "Enter the Gateway Token.",
    "settings.devicesAgentRequired": "Enter an Agent ID.",
    "settings.devicesAgentInvalid": "Agent ID must be an agent-UUIDv4 generated by the client.",
    "settings.memoryOrganizerBackToList": "Back to history list",
    "settings.systemProxyDesc":
      "Applies to: local command environment on the desktop (Bash / background tasks / automation scripts), providers with “Use app proxy” checked, Hook / Cron HTTP tasks, chat image loading, update checks and skill downloads.",
    "settings.workdirDesc":
      "Choose this project's folder. File tools read/write/search within the selected project directory.",
    "settings.workdirPickerTitle": "Select Project Folder",
    "settings.filePickerTitle": "Select File",
    "settings.filePickerDesc": "Pick a file from the desktop device",
    "settings.pathPickerPathLabel": "Path",
    "settings.emptyDir": "This directory is empty",
    "settings.select": "Select",
    "settings.loadingDirs": "Loading directories…",
    "settings.dirLoadFailed": "Failed to read directory: ",
    "settings.noSubdirs": "No subdirectories",
    "settings.tooManyDirs": "Too many directories, results truncated",
    "settings.createFolder": "New Folder",
    "settings.newFolderNamePlaceholder": "New folder name",
    "settings.newFolderSelectParentFirst": "Select a parent folder first",
    "settings.createFolderFailed": "Failed to create folder",
    "settings.remoteAgentIdPlaceholder": "e.g. macbook-pro",
    "settings.remoteAgentIdHint":
      "Unique identifier for this Agent shown in WebUI. Leave empty to use hostname",
    "settings.remoteWebTerminalHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can start and control local project terminals.",
    "settings.remoteWebSshTerminalHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can create and control remote interactive terminals using SSH profiles saved on the desktop.",
    "settings.remoteWebGitHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can run branch, stage, commit, and sync operations on local projects.",
    "settings.remoteWebTunnelsHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can create and close temporary links for localhost or IP-address HTTP services.",
    "settings.remoteHeartbeatHint":
      "Keepalive heartbeat interval for the Gateway connection (effective range 10-60 seconds), used to maintain the connection and detect online status",
    "settings.remoteInfoBanner":
      "When enabled, the local ReactorPro connects to the cloud Gateway over WebSocket (protocol v2). You can remotely send Chat messages, manage Cron tasks, and view history through the WebUI in your browser. All tool execution remains local — the remote end only relays commands and results.",
  },
  "en-US": {
    "app.desktopSettingsSyncFailed": "Failed to sync desktop settings.",
    "app.webSettingsSaveFailed": "Failed to save WebUI settings.",
    "chat.runtime.settingsSyncTitle": "Syncing desktop settings",
    "chat.runtime.protocolIncompatible":
      "This desktop version does not support reliable chat sync. Update ReactorPro desktop before using WebUI chat.",
    "chat.runtime.protocolIncompatiblePlaceholder": "Update ReactorPro desktop to continue",
    "chat.queue.moveDown": "Move down",
    "chat.upload.maxFilesIgnored": "Upload up to {max} files; {count} extra files were ignored",
    "chat.upload.duplicatesMerged": "Merged {count} duplicate files",
    "projectTools.sshLocalForwardHelp":
      "Listens on the desktop machine's 127.0.0.1 only. Leave the local port empty or 0 for auto-assign; leave the remote host empty for 127.0.0.1 on the SSH server.",
    "projectTools.sshLocalForwardListening": "Listening on the desktop machine only",
    "settings.navAgentManagement": "Multi-client Management",
    "settings.devicesTitle": "Multi-client Management",
    "settings.devicesDesc": "Manage Agents connected to this Gateway and their credentials",
    "settings.devicesRefresh": "Refresh",
    "settings.devicesFilterAll": "All",
    "settings.devicesFilterOnline": "Online",
    "settings.devicesFilterOffline": "Offline",
    "settings.devicesFilterEmpty": "No matching clients",
    "settings.devicesFilterEmptyDesc": "Choose another status or refresh and try again.",
    "settings.devicesLoginTitle": "Verify Gateway Token",
    "settings.devicesLoginDesc":
      "The current login is unavailable. Enter the Gateway Token again to continue.",
    "settings.devicesGatewayToken": "Gateway Token",
    "settings.devicesLogin": "Verify",
    "settings.devicesAdd": "Add client",
    "settings.devicesAddTitle": "Add client",
    "settings.devicesAddDesc":
      "Enter the Agent ID generated by the client and issue an independent credential.",
    "settings.devicesName": "Client name",
    "settings.devicesNamePlaceholder": "Optional, for example Office desktop",
    "settings.devicesAgentId": "Agent ID",
    "settings.devicesAgentIdPlaceholder": "Paste the agent-UUID generated by the client",
    "settings.devicesIssueShort": "Issue",
    "settings.devicesRotate": "Rotate",
    "settings.devicesRotateTitle": "Rotate client credential?",
    "settings.devicesRotateDesc":
      "Rotation immediately disconnects the client. The old credential cannot reconnect, and the new plaintext is shown once.",
    "settings.devicesEditName": "Edit",
    "settings.devicesIssuedTitle": "Client credential issued",
    "settings.devicesTokenOnce":
      "This token can be reused for client connections, but its plaintext is shown only once. Copy and store it now.",
    "settings.devicesEmpty": "No registered clients",
    "settings.devicesEmptyDesc":
      "Connect a client or select Add client to issue an independent credential.",
    "settings.devicesLoading": "Loading clients…",
    "settings.devicesOnlineStatus": "Online",
    "settings.devicesOfflineStatus": "Offline",
    "settings.devicesUnknownStatus": "Checking status",
    "settings.devicesIndependentTokenIssued": "Independent credential issued",
    "settings.devicesIndependentTokenMissing": "No independent credential",
    "settings.devicesDelete": "Delete",
    "settings.devicesDeleteTitle": "Delete client?",
    "settings.devicesDeleteDesc":
      "This deletes the record, invalidates its credential, and closes its connection. A client using the shared Gateway Token may register again automatically:",
    "settings.devicesPage": "Page",
    "settings.devicesPrevious": "Previous",
    "settings.devicesNext": "Next",
    "settings.devicesLoadFailed": "Failed to load clients.",
    "settings.devicesIssueFailed": "Failed to issue client credential.",
    "settings.devicesNameUpdateFailed": "Failed to update the client name.",
    "settings.devicesDeleteFailed": "Failed to delete the client.",
    "settings.devicesTokenRequired": "Enter the Gateway Token.",
    "settings.devicesAgentRequired": "Enter an Agent ID.",
    "settings.devicesAgentInvalid": "Agent ID must be an agent-UUIDv4 generated by the client.",
    "settings.memoryOrganizerBackToList": "Back to history list",
    "settings.systemProxyDesc":
      "Applies to: local command environment on the desktop (Bash / background tasks / automation scripts), providers with “Use app proxy” checked, Hook / Cron HTTP tasks, chat image loading, update checks and skill downloads.",
    "settings.workdirDesc":
      "Choose this project's folder. File tools read/write/search within the selected project directory.",
    "settings.workdirPickerTitle": "Select Project Folder",
    "settings.filePickerTitle": "Select File",
    "settings.filePickerDesc": "Pick a file from the desktop device",
    "settings.pathPickerPathLabel": "Path",
    "settings.emptyDir": "This directory is empty",
    "settings.select": "Select",
    "settings.loadingDirs": "Loading directories…",
    "settings.dirLoadFailed": "Failed to read directory: ",
    "settings.noSubdirs": "No subdirectories",
    "settings.tooManyDirs": "Too many directories, results truncated",
    "settings.createFolder": "New Folder",
    "settings.newFolderNamePlaceholder": "New folder name",
    "settings.newFolderSelectParentFirst": "Select a parent folder first",
    "settings.createFolderFailed": "Failed to create folder",
    "settings.remoteAgentIdPlaceholder": "e.g. macbook-pro",
    "settings.remoteAgentIdHint":
      "Unique identifier for this Agent shown in WebUI. Leave empty to use hostname",
    "settings.remoteWebTerminalHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can start and control local project terminals.",
    "settings.remoteWebSshTerminalHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can create and control remote interactive terminals using SSH profiles saved on the desktop.",
    "settings.remoteWebGitHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can run branch, stage, commit, and sync operations on local projects.",
    "settings.remoteWebTunnelsHint":
      "Controlled by the desktop Remote settings. When enabled, authenticated WebUI clients can create and close temporary links for localhost or IP-address HTTP services.",
    "settings.remoteHeartbeatHint":
      "Keepalive heartbeat interval for the Gateway connection (effective range 10-60 seconds), used to maintain the connection and detect online status",
    "settings.remoteInfoBanner":
      "When enabled, the local ReactorPro connects to the cloud Gateway over WebSocket (protocol v2). You can remotely send Chat messages, manage Cron tasks, and view history through the WebUI in your browser. All tool execution remains local — the remote end only relays commands and results.",
  },
};

export const { translations, t } = createHostTranslations(WEBUI_TRANSLATION_OVERRIDES);
