import type { CustomProvider } from "@liveagent/app/lib/settings";

const RESERVED_CUSTOM_HEADER_KEYS = new Set([
  "authorization",
  "x-api-key",
  "x-goog-api-key",
  "anthropic-beta",
  "host",
  "content-length",
]);
// Internal channel namespace of the local reverse proxy: allowing it would let users inject control headers such as
// the proxy token / upstream origin into upstream requests. The reverse proxy also strips this prefix itself; rejecting
// it here on the config side gives clear feedback earlier.
const RESERVED_CUSTOM_HEADER_KEY_PREFIX = "x-liveagent-";
const HTTP_HEADER_TOKEN_PATTERN = /^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;
// Header values allow only visible ASCII and horizontal tab: CR/LF causes header injection, and non-ASCII makes the
// WebView's fetch() throw outright, breaking the whole conversation turn with an error unrelated to the request headers.
const HTTP_HEADER_VALUE_PATTERN = /^[\t\x20-\x7e]*$/;

export type CustomHeader = { key: string; value: string };

export type CustomHeaderImportIssueReason =
  | "invalid-item"
  | "unsupported-value"
  | "invalid-key"
  | "reserved"
  | "invalid-value"
  | "malformed-header";

export type CustomHeaderImportIssue = {
  key?: string;
  reason: CustomHeaderImportIssueReason;
};

export type CustomHeaderImportResult = {
  headers: CustomHeader[];
  issues: CustomHeaderImportIssue[];
};

export type CustomHeaderImportErrorCode =
  | "empty"
  | "invalid-json"
  | "unsupported-json"
  | "unterminated-quote";

export class CustomHeaderImportError extends Error {
  constructor(readonly code: CustomHeaderImportErrorCode) {
    super(code);
    this.name = "CustomHeaderImportError";
  }
}

// Claude Code CLI's SDK fingerprint headers, replicating verbatim the fixed headers sent to /v1/messages by the
// official source claude-code-source (v2.1.88, whose inlined @anthropic-ai/sdk = 0.74.0); the matching UA is in
// CLI_IDENTITY_USER_AGENTS.claude_code -- the version numbers must come as a set, since a mismatch between the SDK
// version and the CLI version in the UA is itself a giveaway.
// anthropic-beta is not here: it is computed per request from the content (a comma-joined beta list), and hardcoding
// a single value would be misleading, so it is listed in RESERVED_CUSTOM_HEADER_KEYS and generated by the request side.
// X-Stainless-OS/Arch/Runtime-Version match the official SDK defaults; the platform-dependent CLI User-Agent is
// generated by buildCliUserAgent from the current runtime environment.
export const ANTHROPIC_DEFAULT_REQUEST_HEADERS = {
  "x-app": "cli",
  "Content-Type": "application/json",
  "X-Stainless-OS": "MacOS",
  "X-Stainless-Arch": "arm64",
  "X-Stainless-Lang": "js",
  "anthropic-version": "2023-06-01",
  "X-Stainless-Runtime": "node",
  "X-Stainless-Timeout": "600",
  // The official SDK client.mjs:468 writes Pascal-Case; HTTP is case-insensitive, but some reverse proxies / risk
  // controls compare literally, so it must match the SDK.
  "X-Stainless-Retry-Count": "0",
  "X-Stainless-Package-Version": "0.74.0",
  "X-Stainless-Runtime-Version": "v26.3.0",
  "anthropic-dangerous-direct-browser-access": "true",
} as const;

function runtimePlatform(): { os: string; arch: string } {
  const nav = typeof navigator !== "undefined" ? navigator : undefined;
  const ua = nav?.userAgent ?? "";
  const os = /Windows/i.test(ua) ? "Windows" : /Macintosh|Mac OS/i.test(ua) ? "MacOS" : "Linux";
  const arch = /arm|aarch/i.test(ua) ? "arm64" : "x86_64";
  return { os, arch };
}

export function getCliRuntimePlatform(): { os: string; arch: string } {
  return runtimePlatform();
}

// Claude Code per-session headers (claude-code-source src/services/api/client.ts:108 / :356).
// The value is a runtime session UUID, so one-click simulation does not hardcode it; the request assembly side fills
// it in when a sessionId is available.
export const CLAUDE_SESSION_ID_HEADER = "X-Claude-Code-Session-Id";
export const CLIENT_REQUEST_ID_HEADER = "x-client-request-id";

// The old Responses path (existing in ReactorPro + some relays) still recognizes these two underscore headers.
export const CODEX_SESSION_ID_HEADER = "session_id";
export const CODEX_CONVERSATION_ID_HEADER = "conversation_id";
// The current Codex CLI (codex-rs/codex-api/src/requests/headers.rs +
// endpoint/responses.rs) sends hyphenated headers instead: session-id / thread-id, and syncs thread-id
// to x-client-request-id.
export const CODEX_OFFICIAL_SESSION_ID_HEADER = "session-id";
export const CODEX_THREAD_ID_HEADER = "thread-id";

// Version numbers of each official CLI: the UA and the accompanying version / client-version headers must share a
// source, since a mismatch is itself a giveaway. claude_code / xai are taken from the user-provided official source
// (claude-code-source package.json = 2.1.88; Grok's current release is 1.0.24; the codex source tree holds the
// placeholder 0.0.0 (bumped only at release), which cannot serve as a true value, so the current release number is used.
const CLAUDE_CLI_VERSION = "2.1.88";
const CODEX_CLI_VERSION = "0.151.0";
// Current grok CLI release; the UA and x-grok-client-version must stay consistent.
const GROK_CLI_VERSION = "1.0.24";

// The two static identity headers Codex CLI always sends on every request besides the UA: originator (codex-rs
// login/src/auth/default_client.rs default_headers(), value codex_cli_rs) and version
// (codex-rs model-provider-info/src/lib.rs, value = CARGO_PKG_VERSION, the same version as the UA).
export const CODEX_ORIGINATOR_HEADER = "originator";
export const CODEX_ORIGINATOR_VALUE = "codex_cli_rs";
export const CODEX_VERSION_HEADER = "version";

// The static client identity headers grok-shell always sends besides the UA (xai-grok-http/src/lib.rs
// process_client_identifier / process_client_mode + xai-grok-shell
// mvp_agent/mod.rs inject_proxy_headers). client-identifier/version/mode are sent by every side; the auth-proxy-only
// X-XAI-Token-Auth / x-authenticateresponse are not part of the default client identity and so are not injected in presets.
const GROK_IDENTITY_HEADERS: readonly CustomHeader[] = [
  { key: "x-grok-client-identifier", value: "grok-shell" },
  { key: "x-grok-client-version", value: GROK_CLI_VERSION },
  { key: "x-grok-client-mode", value: "interactive" },
];

// grok-shell per-turn headers (xai-grok-sampler/src/client.rs GrokRequestHeaders); their values vary with
// conv/req/session, so one-click simulation does not hardcode them.
const GROK_DYNAMIC_HEADER_KEYS = [
  "x-grok-conv-id",
  "x-grok-req-id",
  "x-grok-session-id",
  "x-grok-agent-id",
  "x-grok-model-override",
  "x-grok-turn-idx",
] as const;

const COMMON_CUSTOM_HEADER_KEY_PRESETS = [
  "X-Request-ID",
  "X-User-ID",
  "X-Environment",
  "HTTP-Referer",
  "X-Title",
] as const;

const ANTHROPIC_CUSTOM_HEADER_KEY_PRESETS: readonly string[] = [
  ...Object.keys(ANTHROPIC_DEFAULT_REQUEST_HEADERS),
  CLAUDE_SESSION_ID_HEADER,
  CLIENT_REQUEST_ID_HEADER,
  ...COMMON_CUSTOM_HEADER_KEY_PRESETS,
];

const CODEX_CUSTOM_HEADER_KEY_PRESETS: readonly string[] = [
  CODEX_ORIGINATOR_HEADER,
  CODEX_VERSION_HEADER,
  CODEX_OFFICIAL_SESSION_ID_HEADER,
  CODEX_THREAD_ID_HEADER,
  CLIENT_REQUEST_ID_HEADER,
  CODEX_SESSION_ID_HEADER,
  CODEX_CONVERSATION_ID_HEADER,
  ...COMMON_CUSTOM_HEADER_KEY_PRESETS,
];

const XAI_CUSTOM_HEADER_KEY_PRESETS: readonly string[] = [
  ...GROK_IDENTITY_HEADERS.map((header) => header.key),
  ...GROK_DYNAMIC_HEADER_KEYS,
  ...COMMON_CUSTOM_HEADER_KEY_PRESETS,
];

const CUSTOM_HEADER_KEY_PRESETS: Record<CustomProvider["type"], readonly string[]> = {
  claude_code: ANTHROPIC_CUSTOM_HEADER_KEY_PRESETS,
  codex: CODEX_CUSTOM_HEADER_KEY_PRESETS,
  gemini: COMMON_CUSTOM_HEADER_KEY_PRESETS,
  xai: XAI_CUSTOM_HEADER_KEY_PRESETS,
  deepseek: COMMON_CUSTOM_HEADER_KEY_PRESETS,
};

export function getCustomHeaderKeyPresets(providerId: CustomProvider["type"]): readonly string[] {
  return CUSTOM_HEADER_KEY_PRESETS[providerId];
}

export function isAnthropicOAuthApiKey(apiKey: string | undefined): boolean {
  return Boolean(apiKey?.includes("sk-ant-oat"));
}

// The identity UA written by the "simulate CLI" button, replicating verbatim the User-Agent each official CLI sends
// to the model API: claude-code-source src/utils/http.ts, codex-rs login/src/auth/default_client.rs
// get_codex_user_agent(), grok xai-grok-sampler/src/client.rs. Version numbers come from the three *_CLI_VERSION
// constants above, ensuring the UA and the accompanying version / client-version headers share a source. The
// os/arch/terminal segments are generated from the current runtime machine's platform; the static preview values are
// only for dropdown display.
// These values are written into custom request headers only when the user clicks the button; the request side
// contains no built-in masquerading.
export const CLI_IDENTITY_USER_AGENTS = {
  claude_code: `claude-cli/${CLAUDE_CLI_VERSION} (external, cli)`,
  codex: `codex_cli_rs/${CODEX_CLI_VERSION} (Ubuntu 24.4.0; x86_64) WindowsTerminal`,
  xai: `grok-shell/${GROK_CLI_VERSION} (linux; x86_64)`,
} as const;

export function buildCliUserAgent(type: CliIdentityProviderId): string {
  const version = CLI_IDENTITY_USER_AGENTS[type].match(/\/([0-9][^ ]*)/)?.[1] ?? "0.0.0";
  const { os, arch } = runtimePlatform();
  if (type === "claude_code") return `claude-cli/${version} (external, cli)`;
  if (type === "codex") return `codex_cli_rs/${version} (${os}; ${arch})`;
  return `grok-shell/${version} (${os.toLowerCase()}; ${arch})`;
}

export type CliIdentityProviderId = keyof typeof CLI_IDENTITY_USER_AGENTS;

export const CLI_IDENTITY_PROVIDER_IDS = Object.keys(
  CLI_IDENTITY_USER_AGENTS,
) as CliIdentityProviderId[];

export function isCliIdentityProviderId(value: string): value is CliIdentityProviderId {
  return Object.hasOwn(CLI_IDENTITY_USER_AGENTS, value);
}

/** The dropdown puts the identity profile matching the current provider first, reducing the chance of picking the wrong one. */
export function listCliIdentityProviderIds(preferred?: string): readonly CliIdentityProviderId[] {
  if (!preferred || !isCliIdentityProviderId(preferred)) return CLI_IDENTITY_PROVIDER_IDS;
  return [preferred, ...CLI_IDENTITY_PROVIDER_IDS.filter((id) => id !== preferred)];
}

// The full set of CLI identity headers written by the one-click simulate button. Content-Type is decided by the
// request side from the body and does not enter the user-editable list; per-session random dynamic headers (Claude's
// X-Claude-Code-Session-Id / x-client-request-id; Codex's session-id/thread-id; Grok's
// x-grok-conv-id/req-id/session-id/turn-idx) masquerading as fixed strings would be more suspicious than absent, so
// they are always left for the request assembly side to fill from sessionId, or for the user to fill (their key names
// are already in the respective presets).
export function buildCliIdentityHeaders(type: CliIdentityProviderId): CustomHeader[] {
  const headers: CustomHeader[] = [{ key: "User-Agent", value: buildCliUserAgent(type) }];
  if (type === "claude_code") {
    // Write the whole Anthropic SDK fingerprint header set (except Content-Type, see above).
    for (const [key, value] of Object.entries(ANTHROPIC_DEFAULT_REQUEST_HEADERS)) {
      if (key.toLowerCase() === "content-type") continue;
      headers.push({ key, value });
    }
  } else if (type === "codex") {
    // The two static identity headers Codex CLI always sends per request: originator + version.
    headers.push({ key: CODEX_ORIGINATOR_HEADER, value: CODEX_ORIGINATOR_VALUE });
    headers.push({ key: CODEX_VERSION_HEADER, value: CODEX_CLI_VERSION });
  } else if (type === "xai") {
    // grok-shell's static client identity headers (including the cli-chat-proxy marker).
    for (const header of GROK_IDENTITY_HEADERS) {
      headers.push({ ...header });
    }
  }
  return headers;
}

// All header names under each CLI: the static identity headers written by one click + the per-session dynamic
// headers the user may fill by hand. When switching identity, every other CLI's headers are stripped wholesale per
// this table -- overwriting by name alone would only swap the User-Agent, leaving the previous vendor's x-app /
// X-Stainless-* / originator / x-grok-* behind to form a fake fingerprint resembling no vendor. Content-Type is
// excluded (the button does not write it, and it is not exclusive to any vendor).
const CLI_IDENTITY_HEADER_FAMILIES: Record<CliIdentityProviderId, readonly string[]> = {
  claude_code: [
    ...buildCliIdentityHeaders("claude_code").map((header) => header.key),
    CLAUDE_SESSION_ID_HEADER,
    CLIENT_REQUEST_ID_HEADER,
  ],
  codex: [
    ...buildCliIdentityHeaders("codex").map((header) => header.key),
    CODEX_OFFICIAL_SESSION_ID_HEADER,
    CODEX_THREAD_ID_HEADER,
    CLIENT_REQUEST_ID_HEADER,
    CODEX_SESSION_ID_HEADER,
    CODEX_CONVERSATION_ID_HEADER,
  ],
  xai: [...buildCliIdentityHeaders("xai").map((header) => header.key), ...GROK_DYNAMIC_HEADER_KEYS],
};

export type CliIdentityApplyResult = {
  headers: CustomHeader[];
  importedCount: number;
  overwrittenCount: number;
  removedCount: number;
};

/**
 * Apply/switch CLI identity: first strip all headers under other CLI families (including user-filled dynamic
 * headers), then merge in the selected CLI's full static identity header set (overwriting by name). The selected
 * CLI's own dynamic headers (e.g. Codex's session-id) keep the user-filled value; business headers not belonging to
 * any CLI family are left untouched.
 */
export function applyCliIdentity(
  current: readonly CustomHeader[],
  identity: CliIdentityProviderId,
): CliIdentityApplyResult {
  const own = new Set(CLI_IDENTITY_HEADER_FAMILIES[identity].map((key) => key.toLowerCase()));
  const foreign = new Set<string>();
  for (const id of CLI_IDENTITY_PROVIDER_IDS) {
    if (id === identity) continue;
    for (const key of CLI_IDENTITY_HEADER_FAMILIES[id]) {
      const lower = key.toLowerCase();
      if (!own.has(lower)) foreign.add(lower);
    }
  }
  const kept = current.filter((header) => !foreign.has(header.key.toLowerCase()));
  const merged = mergeImportedCustomHeaders(kept, buildCliIdentityHeaders(identity));
  return { ...merged, removedCount: current.length - kept.length };
}

function findHeaderKey(
  headers: Record<string, string | null | undefined>,
  name: string,
): string | undefined {
  const expected = name.toLowerCase();
  return Object.keys(headers).find((key) => key.toLowerCase() === expected);
}

export function isValidCustomHeaderKey(key: string): boolean {
  return HTTP_HEADER_TOKEN_PATTERN.test(key);
}

export function isValidCustomHeaderValue(value: string): boolean {
  return HTTP_HEADER_VALUE_PATTERN.test(value);
}

export function isReservedCustomHeaderKey(key: string): boolean {
  const normalized = key.toLowerCase();
  return (
    RESERVED_CUSTOM_HEADER_KEYS.has(normalized) ||
    normalized.startsWith(RESERVED_CUSTOM_HEADER_KEY_PREFIX)
  );
}
function issueKey(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const safe = value.replace(/[\r\n]+/g, " ").trim();
  return safe || undefined;
}

function addImportedHeader(
  headers: CustomHeader[],
  issues: CustomHeaderImportIssue[],
  keyValue: unknown,
  headerValue: unknown,
): void {
  if (typeof keyValue !== "string") {
    issues.push({ reason: "invalid-item" });
    return;
  }

  const key = keyValue;
  if (
    typeof headerValue !== "string" &&
    typeof headerValue !== "number" &&
    typeof headerValue !== "boolean"
  ) {
    issues.push({ key: issueKey(key), reason: "unsupported-value" });
    return;
  }
  if (!isValidCustomHeaderKey(key)) {
    issues.push({ key: issueKey(key), reason: "invalid-key" });
    return;
  }
  if (isReservedCustomHeaderKey(key)) {
    issues.push({ key, reason: "reserved" });
    return;
  }

  const value = String(headerValue);
  if (!isValidCustomHeaderValue(value)) {
    issues.push({ key, reason: "invalid-value" });
    return;
  }

  const existingIndex = headers.findIndex(
    (header) => header.key.toLowerCase() === key.toLowerCase(),
  );
  const next = { key, value };
  if (existingIndex >= 0) headers[existingIndex] = next;
  else headers.push(next);
}

function tokenizeCurl(command: string): string[] {
  const normalized = command.replace(/[\\`^][ \t]*\r?\n/g, " ");
  const tokens: string[] = [];
  let token = "";
  let quote: "'" | '"' | null = null;
  let started = false;

  for (let index = 0; index < normalized.length; index += 1) {
    const character = normalized[index];
    if (quote) {
      if (character === quote) {
        quote = null;
        continue;
      }
      if (
        character === "\\" &&
        quote === '"' &&
        index + 1 < normalized.length &&
        ['"', "\\"].includes(normalized[index + 1])
      ) {
        token += normalized[index + 1];
        index += 1;
        continue;
      }
      token += character;
      continue;
    }

    if (character === "'" || character === '"') {
      quote = character;
      started = true;
      continue;
    }
    if (/\s/.test(character)) {
      if (started) {
        tokens.push(token);
        token = "";
        started = false;
      }
      continue;
    }
    if (
      character === "\\" &&
      index + 1 < normalized.length &&
      (/\s/.test(normalized[index + 1]) ||
        normalized[index + 1] === "'" ||
        normalized[index + 1] === '"')
    ) {
      token += normalized[index + 1];
      started = true;
      index += 1;
      continue;
    }
    token += character;
    started = true;
  }

  if (quote) throw new CustomHeaderImportError("unterminated-quote");
  if (started) tokens.push(token);
  return tokens;
}

function parseCurlHeaders(input: string): CustomHeaderImportResult {
  const tokens = tokenizeCurl(input);
  const headers: CustomHeader[] = [];
  const issues: CustomHeaderImportIssue[] = [];

  for (let index = 0; index < tokens.length; index += 1) {
    const token = tokens[index];
    let rawHeader: string | undefined;
    if (token === "-H" || token === "--header") {
      rawHeader = tokens[index + 1];
      index += 1;
    } else if (token.startsWith("--header=")) {
      rawHeader = token.slice("--header=".length);
    } else {
      continue;
    }

    if (rawHeader === undefined) {
      issues.push({ reason: "malformed-header" });
      continue;
    }
    const separatorIndex = rawHeader.indexOf(":");
    if (separatorIndex < 0) {
      issues.push({ reason: "malformed-header" });
      continue;
    }
    addImportedHeader(
      headers,
      issues,
      rawHeader.slice(0, separatorIndex).trim(),
      rawHeader.slice(separatorIndex + 1).trim(),
    );
  }

  return { headers, issues };
}

export function parseCustomHeadersImport(input: string): CustomHeaderImportResult {
  const trimmed = input.trim();
  if (!trimmed) throw new CustomHeaderImportError("empty");

  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(trimmed);
    } catch {
      throw new CustomHeaderImportError("invalid-json");
    }

    const headers: CustomHeader[] = [];
    const issues: CustomHeaderImportIssue[] = [];
    if (Array.isArray(parsed)) {
      for (const item of parsed) {
        if (!item || typeof item !== "object" || Array.isArray(item)) {
          issues.push({ reason: "invalid-item" });
          continue;
        }
        const record = item as Record<string, unknown>;
        addImportedHeader(headers, issues, record.key, record.value);
      }
    } else if (parsed && typeof parsed === "object") {
      for (const [key, value] of Object.entries(parsed)) {
        addImportedHeader(headers, issues, key, value);
      }
    } else {
      throw new CustomHeaderImportError("unsupported-json");
    }
    return { headers, issues };
  }

  return parseCurlHeaders(trimmed);
}

export function mergeImportedCustomHeaders(
  current: readonly CustomHeader[],
  imported: readonly CustomHeader[],
): { headers: CustomHeader[]; importedCount: number; overwrittenCount: number } {
  let headers = current.map((header) => ({ ...header }));
  let overwrittenCount = 0;

  for (const importedHeader of imported) {
    const expected = importedHeader.key.toLowerCase();
    const firstIndex = headers.findIndex((header) => header.key.toLowerCase() === expected);
    if (firstIndex < 0) {
      headers.push({ ...importedHeader });
      continue;
    }

    overwrittenCount += 1;
    headers = headers.filter(
      (header, index) => index === firstIndex || header.key.toLowerCase() !== expected,
    );
    headers[firstIndex] = { ...importedHeader };
  }

  return { headers, importedCount: imported.length, overwrittenCount };
}
export function mergeCustomHeaders(
  base: Record<string, string>,
  customHeaders?: readonly CustomHeader[],
): Record<string, string> {
  const merged = { ...base };

  for (const header of customHeaders ?? []) {
    if (
      !isValidCustomHeaderKey(header.key) ||
      !isValidCustomHeaderValue(header.value) ||
      isReservedCustomHeaderKey(header.key)
    ) {
      continue;
    }

    const existingKey = findHeaderKey(merged, header.key);
    if (existingKey !== undefined) delete merged[existingKey];
    merged[header.key] = header.value;
  }

  return merged;
}
